<a href="https://colab.research.google.com/github/Atif-Azmi/Machine-Learning/blob/main/class01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as mp
import pandas as pd

In [3]:
df=pd.read_csv('/content/placement.csv')

In [5]:
df.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [6]:
df.tail()

    Unnamed: 0  cgpa     iq  placement
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

In [7]:
df=df.iloc[:,1:] #isme : means select all rows , 1: means from 1 index select ,then by default index 0 wala column remove ho jyega

In [8]:
df.head()

   cgpa     iq  placement
0   6.8  123.0          1
1   5.9  106.0          0
2   5.3  121.0          0
3   7.4  132.0          1
4   5.8  142.0          0

In [10]:
df.shape

(100, 3)

In [12]:
# Steps

# 0. Preprocess + EDA + Feature Selection
# 1. Extract input and output cols
# 2. Scale the values
# 3. Train test split
# 4. Train the model
# 5. Evaluate the model/model selection
# 6. Deploy the model